// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back-end/merchant/internal/data/ent/merchantchannelbind"
	"back-end/merchant/internal/data/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MerchantChannelBindQuery is the builder for querying MerchantChannelBind entities.
type MerchantChannelBindQuery struct {
	config
	ctx        *QueryContext
	order      []merchantchannelbind.OrderOption
	inters     []Interceptor
	predicates []predicate.MerchantChannelBind
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MerchantChannelBindQuery builder.
func (mcbq *MerchantChannelBindQuery) Where(ps ...predicate.MerchantChannelBind) *MerchantChannelBindQuery {
	mcbq.predicates = append(mcbq.predicates, ps...)
	return mcbq
}

// Limit the number of records to be returned by this query.
func (mcbq *MerchantChannelBindQuery) Limit(limit int) *MerchantChannelBindQuery {
	mcbq.ctx.Limit = &limit
	return mcbq
}

// Offset to start from.
func (mcbq *MerchantChannelBindQuery) Offset(offset int) *MerchantChannelBindQuery {
	mcbq.ctx.Offset = &offset
	return mcbq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mcbq *MerchantChannelBindQuery) Unique(unique bool) *MerchantChannelBindQuery {
	mcbq.ctx.Unique = &unique
	return mcbq
}

// Order specifies how the records should be ordered.
func (mcbq *MerchantChannelBindQuery) Order(o ...merchantchannelbind.OrderOption) *MerchantChannelBindQuery {
	mcbq.order = append(mcbq.order, o...)
	return mcbq
}

// First returns the first MerchantChannelBind entity from the query.
// Returns a *NotFoundError when no MerchantChannelBind was found.
func (mcbq *MerchantChannelBindQuery) First(ctx context.Context) (*MerchantChannelBind, error) {
	nodes, err := mcbq.Limit(1).All(setContextOp(ctx, mcbq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{merchantchannelbind.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mcbq *MerchantChannelBindQuery) FirstX(ctx context.Context) *MerchantChannelBind {
	node, err := mcbq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MerchantChannelBind ID from the query.
// Returns a *NotFoundError when no MerchantChannelBind ID was found.
func (mcbq *MerchantChannelBindQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = mcbq.Limit(1).IDs(setContextOp(ctx, mcbq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{merchantchannelbind.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mcbq *MerchantChannelBindQuery) FirstIDX(ctx context.Context) int32 {
	id, err := mcbq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MerchantChannelBind entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MerchantChannelBind entity is found.
// Returns a *NotFoundError when no MerchantChannelBind entities are found.
func (mcbq *MerchantChannelBindQuery) Only(ctx context.Context) (*MerchantChannelBind, error) {
	nodes, err := mcbq.Limit(2).All(setContextOp(ctx, mcbq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{merchantchannelbind.Label}
	default:
		return nil, &NotSingularError{merchantchannelbind.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mcbq *MerchantChannelBindQuery) OnlyX(ctx context.Context) *MerchantChannelBind {
	node, err := mcbq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MerchantChannelBind ID in the query.
// Returns a *NotSingularError when more than one MerchantChannelBind ID is found.
// Returns a *NotFoundError when no entities are found.
func (mcbq *MerchantChannelBindQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = mcbq.Limit(2).IDs(setContextOp(ctx, mcbq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{merchantchannelbind.Label}
	default:
		err = &NotSingularError{merchantchannelbind.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mcbq *MerchantChannelBindQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := mcbq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MerchantChannelBinds.
func (mcbq *MerchantChannelBindQuery) All(ctx context.Context) ([]*MerchantChannelBind, error) {
	ctx = setContextOp(ctx, mcbq.ctx, "All")
	if err := mcbq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MerchantChannelBind, *MerchantChannelBindQuery]()
	return withInterceptors[[]*MerchantChannelBind](ctx, mcbq, qr, mcbq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mcbq *MerchantChannelBindQuery) AllX(ctx context.Context) []*MerchantChannelBind {
	nodes, err := mcbq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MerchantChannelBind IDs.
func (mcbq *MerchantChannelBindQuery) IDs(ctx context.Context) (ids []int32, err error) {
	if mcbq.ctx.Unique == nil && mcbq.path != nil {
		mcbq.Unique(true)
	}
	ctx = setContextOp(ctx, mcbq.ctx, "IDs")
	if err = mcbq.Select(merchantchannelbind.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mcbq *MerchantChannelBindQuery) IDsX(ctx context.Context) []int32 {
	ids, err := mcbq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mcbq *MerchantChannelBindQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mcbq.ctx, "Count")
	if err := mcbq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mcbq, querierCount[*MerchantChannelBindQuery](), mcbq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mcbq *MerchantChannelBindQuery) CountX(ctx context.Context) int {
	count, err := mcbq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mcbq *MerchantChannelBindQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mcbq.ctx, "Exist")
	switch _, err := mcbq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mcbq *MerchantChannelBindQuery) ExistX(ctx context.Context) bool {
	exist, err := mcbq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MerchantChannelBindQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mcbq *MerchantChannelBindQuery) Clone() *MerchantChannelBindQuery {
	if mcbq == nil {
		return nil
	}
	return &MerchantChannelBindQuery{
		config:     mcbq.config,
		ctx:        mcbq.ctx.Clone(),
		order:      append([]merchantchannelbind.OrderOption{}, mcbq.order...),
		inters:     append([]Interceptor{}, mcbq.inters...),
		predicates: append([]predicate.MerchantChannelBind{}, mcbq.predicates...),
		// clone intermediate query.
		sql:  mcbq.sql.Clone(),
		path: mcbq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MerchantID int32 `json:"merchant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MerchantChannelBind.Query().
//		GroupBy(merchantchannelbind.FieldMerchantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mcbq *MerchantChannelBindQuery) GroupBy(field string, fields ...string) *MerchantChannelBindGroupBy {
	mcbq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MerchantChannelBindGroupBy{build: mcbq}
	grbuild.flds = &mcbq.ctx.Fields
	grbuild.label = merchantchannelbind.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MerchantID int32 `json:"merchant_id,omitempty"`
//	}
//
//	client.MerchantChannelBind.Query().
//		Select(merchantchannelbind.FieldMerchantID).
//		Scan(ctx, &v)
func (mcbq *MerchantChannelBindQuery) Select(fields ...string) *MerchantChannelBindSelect {
	mcbq.ctx.Fields = append(mcbq.ctx.Fields, fields...)
	sbuild := &MerchantChannelBindSelect{MerchantChannelBindQuery: mcbq}
	sbuild.label = merchantchannelbind.Label
	sbuild.flds, sbuild.scan = &mcbq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MerchantChannelBindSelect configured with the given aggregations.
func (mcbq *MerchantChannelBindQuery) Aggregate(fns ...AggregateFunc) *MerchantChannelBindSelect {
	return mcbq.Select().Aggregate(fns...)
}

func (mcbq *MerchantChannelBindQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mcbq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mcbq); err != nil {
				return err
			}
		}
	}
	for _, f := range mcbq.ctx.Fields {
		if !merchantchannelbind.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mcbq.path != nil {
		prev, err := mcbq.path(ctx)
		if err != nil {
			return err
		}
		mcbq.sql = prev
	}
	return nil
}

func (mcbq *MerchantChannelBindQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MerchantChannelBind, error) {
	var (
		nodes = []*MerchantChannelBind{}
		_spec = mcbq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MerchantChannelBind).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MerchantChannelBind{config: mcbq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mcbq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mcbq *MerchantChannelBindQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mcbq.querySpec()
	_spec.Node.Columns = mcbq.ctx.Fields
	if len(mcbq.ctx.Fields) > 0 {
		_spec.Unique = mcbq.ctx.Unique != nil && *mcbq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mcbq.driver, _spec)
}

func (mcbq *MerchantChannelBindQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(merchantchannelbind.Table, merchantchannelbind.Columns, sqlgraph.NewFieldSpec(merchantchannelbind.FieldID, field.TypeInt32))
	_spec.From = mcbq.sql
	if unique := mcbq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mcbq.path != nil {
		_spec.Unique = true
	}
	if fields := mcbq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, merchantchannelbind.FieldID)
		for i := range fields {
			if fields[i] != merchantchannelbind.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mcbq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mcbq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mcbq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mcbq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mcbq *MerchantChannelBindQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mcbq.driver.Dialect())
	t1 := builder.Table(merchantchannelbind.Table)
	columns := mcbq.ctx.Fields
	if len(columns) == 0 {
		columns = merchantchannelbind.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mcbq.sql != nil {
		selector = mcbq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mcbq.ctx.Unique != nil && *mcbq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mcbq.predicates {
		p(selector)
	}
	for _, p := range mcbq.order {
		p(selector)
	}
	if offset := mcbq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mcbq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MerchantChannelBindGroupBy is the group-by builder for MerchantChannelBind entities.
type MerchantChannelBindGroupBy struct {
	selector
	build *MerchantChannelBindQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mcbgb *MerchantChannelBindGroupBy) Aggregate(fns ...AggregateFunc) *MerchantChannelBindGroupBy {
	mcbgb.fns = append(mcbgb.fns, fns...)
	return mcbgb
}

// Scan applies the selector query and scans the result into the given value.
func (mcbgb *MerchantChannelBindGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mcbgb.build.ctx, "GroupBy")
	if err := mcbgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MerchantChannelBindQuery, *MerchantChannelBindGroupBy](ctx, mcbgb.build, mcbgb, mcbgb.build.inters, v)
}

func (mcbgb *MerchantChannelBindGroupBy) sqlScan(ctx context.Context, root *MerchantChannelBindQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mcbgb.fns))
	for _, fn := range mcbgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mcbgb.flds)+len(mcbgb.fns))
		for _, f := range *mcbgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mcbgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mcbgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MerchantChannelBindSelect is the builder for selecting fields of MerchantChannelBind entities.
type MerchantChannelBindSelect struct {
	*MerchantChannelBindQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mcbs *MerchantChannelBindSelect) Aggregate(fns ...AggregateFunc) *MerchantChannelBindSelect {
	mcbs.fns = append(mcbs.fns, fns...)
	return mcbs
}

// Scan applies the selector query and scans the result into the given value.
func (mcbs *MerchantChannelBindSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mcbs.ctx, "Select")
	if err := mcbs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MerchantChannelBindQuery, *MerchantChannelBindSelect](ctx, mcbs.MerchantChannelBindQuery, mcbs, mcbs.inters, v)
}

func (mcbs *MerchantChannelBindSelect) sqlScan(ctx context.Context, root *MerchantChannelBindQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mcbs.fns))
	for _, fn := range mcbs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mcbs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mcbs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
