// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back-end/merchant/internal/data/ent/schema"
	"back-end/merchant/internal/data/ent/sysmenu"
	"back-end/merchant/internal/data/ent/syspermissions"
	"back-end/merchant/internal/data/ent/sysrolemenu"
	"back-end/merchant/internal/data/ent/sysrolepermissions"
	"back-end/merchant/internal/data/ent/sysroles"
	"back-end/merchant/internal/data/ent/sysroleusers"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	sysmenuFields := schema.SysMenu{}.Fields()
	_ = sysmenuFields
	// sysmenuDescParentID is the schema descriptor for parent_id field.
	sysmenuDescParentID := sysmenuFields[1].Descriptor()
	// sysmenu.DefaultParentID holds the default value on creation for the parent_id field.
	sysmenu.DefaultParentID = sysmenuDescParentID.Default.(int64)
	// sysmenuDescShow is the schema descriptor for show field.
	sysmenuDescShow := sysmenuFields[5].Descriptor()
	// sysmenu.DefaultShow holds the default value on creation for the show field.
	sysmenu.DefaultShow = sysmenuDescShow.Default.(int8)
	// sysmenuDescSort is the schema descriptor for sort field.
	sysmenuDescSort := sysmenuFields[6].Descriptor()
	// sysmenu.DefaultSort holds the default value on creation for the sort field.
	sysmenu.DefaultSort = sysmenuDescSort.Default.(int32)
	// sysmenuDescCreateTime is the schema descriptor for create_time field.
	sysmenuDescCreateTime := sysmenuFields[7].Descriptor()
	// sysmenu.DefaultCreateTime holds the default value on creation for the create_time field.
	sysmenu.DefaultCreateTime = sysmenuDescCreateTime.Default.(int32)
	// sysmenuDescUpdateTime is the schema descriptor for update_time field.
	sysmenuDescUpdateTime := sysmenuFields[8].Descriptor()
	// sysmenu.DefaultUpdateTime holds the default value on creation for the update_time field.
	sysmenu.DefaultUpdateTime = sysmenuDescUpdateTime.Default.(int32)
	syspermissionsFields := schema.SysPermissions{}.Fields()
	_ = syspermissionsFields
	// syspermissionsDescMenuID is the schema descriptor for menu_id field.
	syspermissionsDescMenuID := syspermissionsFields[1].Descriptor()
	// syspermissions.DefaultMenuID holds the default value on creation for the menu_id field.
	syspermissions.DefaultMenuID = syspermissionsDescMenuID.Default.(int64)
	// syspermissionsDescCreateTime is the schema descriptor for create_time field.
	syspermissionsDescCreateTime := syspermissionsFields[6].Descriptor()
	// syspermissions.DefaultCreateTime holds the default value on creation for the create_time field.
	syspermissions.DefaultCreateTime = syspermissionsDescCreateTime.Default.(int32)
	// syspermissionsDescUpdateTime is the schema descriptor for update_time field.
	syspermissionsDescUpdateTime := syspermissionsFields[7].Descriptor()
	// syspermissions.DefaultUpdateTime holds the default value on creation for the update_time field.
	syspermissions.DefaultUpdateTime = syspermissionsDescUpdateTime.Default.(int32)
	sysrolemenuFields := schema.SysRoleMenu{}.Fields()
	_ = sysrolemenuFields
	// sysrolemenuDescCreateTime is the schema descriptor for create_time field.
	sysrolemenuDescCreateTime := sysrolemenuFields[3].Descriptor()
	// sysrolemenu.DefaultCreateTime holds the default value on creation for the create_time field.
	sysrolemenu.DefaultCreateTime = sysrolemenuDescCreateTime.Default.(int32)
	// sysrolemenuDescUpdateTime is the schema descriptor for update_time field.
	sysrolemenuDescUpdateTime := sysrolemenuFields[4].Descriptor()
	// sysrolemenu.DefaultUpdateTime holds the default value on creation for the update_time field.
	sysrolemenu.DefaultUpdateTime = sysrolemenuDescUpdateTime.Default.(int32)
	sysrolepermissionsFields := schema.SysRolePermissions{}.Fields()
	_ = sysrolepermissionsFields
	// sysrolepermissionsDescCreateTime is the schema descriptor for create_time field.
	sysrolepermissionsDescCreateTime := sysrolepermissionsFields[3].Descriptor()
	// sysrolepermissions.DefaultCreateTime holds the default value on creation for the create_time field.
	sysrolepermissions.DefaultCreateTime = sysrolepermissionsDescCreateTime.Default.(int32)
	// sysrolepermissionsDescUpdateTime is the schema descriptor for update_time field.
	sysrolepermissionsDescUpdateTime := sysrolepermissionsFields[4].Descriptor()
	// sysrolepermissions.DefaultUpdateTime holds the default value on creation for the update_time field.
	sysrolepermissions.DefaultUpdateTime = sysrolepermissionsDescUpdateTime.Default.(int32)
	sysroleusersFields := schema.SysRoleUsers{}.Fields()
	_ = sysroleusersFields
	// sysroleusersDescUpdateTime is the schema descriptor for update_time field.
	sysroleusersDescUpdateTime := sysroleusersFields[4].Descriptor()
	// sysroleusers.DefaultUpdateTime holds the default value on creation for the update_time field.
	sysroleusers.DefaultUpdateTime = sysroleusersDescUpdateTime.Default.(int32)
	sysrolesFields := schema.SysRoles{}.Fields()
	_ = sysrolesFields
	// sysrolesDescCreateTime is the schema descriptor for create_time field.
	sysrolesDescCreateTime := sysrolesFields[5].Descriptor()
	// sysroles.DefaultCreateTime holds the default value on creation for the create_time field.
	sysroles.DefaultCreateTime = sysrolesDescCreateTime.Default.(int32)
	// sysrolesDescUpdateTime is the schema descriptor for update_time field.
	sysrolesDescUpdateTime := sysrolesFields[6].Descriptor()
	// sysroles.DefaultUpdateTime holds the default value on creation for the update_time field.
	sysroles.DefaultUpdateTime = sysrolesDescUpdateTime.Default.(int32)
}
