// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back-end/merchant/internal/data/ent/predicate"
	"back-end/merchant/internal/data/ent/sysroleusers"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysRoleUsersQuery is the builder for querying SysRoleUsers entities.
type SysRoleUsersQuery struct {
	config
	ctx        *QueryContext
	order      []sysroleusers.OrderOption
	inters     []Interceptor
	predicates []predicate.SysRoleUsers
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SysRoleUsersQuery builder.
func (sruq *SysRoleUsersQuery) Where(ps ...predicate.SysRoleUsers) *SysRoleUsersQuery {
	sruq.predicates = append(sruq.predicates, ps...)
	return sruq
}

// Limit the number of records to be returned by this query.
func (sruq *SysRoleUsersQuery) Limit(limit int) *SysRoleUsersQuery {
	sruq.ctx.Limit = &limit
	return sruq
}

// Offset to start from.
func (sruq *SysRoleUsersQuery) Offset(offset int) *SysRoleUsersQuery {
	sruq.ctx.Offset = &offset
	return sruq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sruq *SysRoleUsersQuery) Unique(unique bool) *SysRoleUsersQuery {
	sruq.ctx.Unique = &unique
	return sruq
}

// Order specifies how the records should be ordered.
func (sruq *SysRoleUsersQuery) Order(o ...sysroleusers.OrderOption) *SysRoleUsersQuery {
	sruq.order = append(sruq.order, o...)
	return sruq
}

// First returns the first SysRoleUsers entity from the query.
// Returns a *NotFoundError when no SysRoleUsers was found.
func (sruq *SysRoleUsersQuery) First(ctx context.Context) (*SysRoleUsers, error) {
	nodes, err := sruq.Limit(1).All(setContextOp(ctx, sruq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sysroleusers.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sruq *SysRoleUsersQuery) FirstX(ctx context.Context) *SysRoleUsers {
	node, err := sruq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SysRoleUsers ID from the query.
// Returns a *NotFoundError when no SysRoleUsers ID was found.
func (sruq *SysRoleUsersQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = sruq.Limit(1).IDs(setContextOp(ctx, sruq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sysroleusers.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sruq *SysRoleUsersQuery) FirstIDX(ctx context.Context) int32 {
	id, err := sruq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SysRoleUsers entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SysRoleUsers entity is found.
// Returns a *NotFoundError when no SysRoleUsers entities are found.
func (sruq *SysRoleUsersQuery) Only(ctx context.Context) (*SysRoleUsers, error) {
	nodes, err := sruq.Limit(2).All(setContextOp(ctx, sruq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sysroleusers.Label}
	default:
		return nil, &NotSingularError{sysroleusers.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sruq *SysRoleUsersQuery) OnlyX(ctx context.Context) *SysRoleUsers {
	node, err := sruq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SysRoleUsers ID in the query.
// Returns a *NotSingularError when more than one SysRoleUsers ID is found.
// Returns a *NotFoundError when no entities are found.
func (sruq *SysRoleUsersQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = sruq.Limit(2).IDs(setContextOp(ctx, sruq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sysroleusers.Label}
	default:
		err = &NotSingularError{sysroleusers.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sruq *SysRoleUsersQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := sruq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SysRoleUsersSlice.
func (sruq *SysRoleUsersQuery) All(ctx context.Context) ([]*SysRoleUsers, error) {
	ctx = setContextOp(ctx, sruq.ctx, "All")
	if err := sruq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SysRoleUsers, *SysRoleUsersQuery]()
	return withInterceptors[[]*SysRoleUsers](ctx, sruq, qr, sruq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sruq *SysRoleUsersQuery) AllX(ctx context.Context) []*SysRoleUsers {
	nodes, err := sruq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SysRoleUsers IDs.
func (sruq *SysRoleUsersQuery) IDs(ctx context.Context) (ids []int32, err error) {
	if sruq.ctx.Unique == nil && sruq.path != nil {
		sruq.Unique(true)
	}
	ctx = setContextOp(ctx, sruq.ctx, "IDs")
	if err = sruq.Select(sysroleusers.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sruq *SysRoleUsersQuery) IDsX(ctx context.Context) []int32 {
	ids, err := sruq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sruq *SysRoleUsersQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sruq.ctx, "Count")
	if err := sruq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sruq, querierCount[*SysRoleUsersQuery](), sruq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sruq *SysRoleUsersQuery) CountX(ctx context.Context) int {
	count, err := sruq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sruq *SysRoleUsersQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sruq.ctx, "Exist")
	switch _, err := sruq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sruq *SysRoleUsersQuery) ExistX(ctx context.Context) bool {
	exist, err := sruq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SysRoleUsersQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sruq *SysRoleUsersQuery) Clone() *SysRoleUsersQuery {
	if sruq == nil {
		return nil
	}
	return &SysRoleUsersQuery{
		config:     sruq.config,
		ctx:        sruq.ctx.Clone(),
		order:      append([]sysroleusers.OrderOption{}, sruq.order...),
		inters:     append([]Interceptor{}, sruq.inters...),
		predicates: append([]predicate.SysRoleUsers{}, sruq.predicates...),
		// clone intermediate query.
		sql:  sruq.sql.Clone(),
		path: sruq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RoleID int64 `json:"role_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SysRoleUsers.Query().
//		GroupBy(sysroleusers.FieldRoleID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sruq *SysRoleUsersQuery) GroupBy(field string, fields ...string) *SysRoleUsersGroupBy {
	sruq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SysRoleUsersGroupBy{build: sruq}
	grbuild.flds = &sruq.ctx.Fields
	grbuild.label = sysroleusers.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RoleID int64 `json:"role_id,omitempty"`
//	}
//
//	client.SysRoleUsers.Query().
//		Select(sysroleusers.FieldRoleID).
//		Scan(ctx, &v)
func (sruq *SysRoleUsersQuery) Select(fields ...string) *SysRoleUsersSelect {
	sruq.ctx.Fields = append(sruq.ctx.Fields, fields...)
	sbuild := &SysRoleUsersSelect{SysRoleUsersQuery: sruq}
	sbuild.label = sysroleusers.Label
	sbuild.flds, sbuild.scan = &sruq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SysRoleUsersSelect configured with the given aggregations.
func (sruq *SysRoleUsersQuery) Aggregate(fns ...AggregateFunc) *SysRoleUsersSelect {
	return sruq.Select().Aggregate(fns...)
}

func (sruq *SysRoleUsersQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sruq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sruq); err != nil {
				return err
			}
		}
	}
	for _, f := range sruq.ctx.Fields {
		if !sysroleusers.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sruq.path != nil {
		prev, err := sruq.path(ctx)
		if err != nil {
			return err
		}
		sruq.sql = prev
	}
	return nil
}

func (sruq *SysRoleUsersQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SysRoleUsers, error) {
	var (
		nodes = []*SysRoleUsers{}
		_spec = sruq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SysRoleUsers).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SysRoleUsers{config: sruq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sruq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (sruq *SysRoleUsersQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sruq.querySpec()
	_spec.Node.Columns = sruq.ctx.Fields
	if len(sruq.ctx.Fields) > 0 {
		_spec.Unique = sruq.ctx.Unique != nil && *sruq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sruq.driver, _spec)
}

func (sruq *SysRoleUsersQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sysroleusers.Table, sysroleusers.Columns, sqlgraph.NewFieldSpec(sysroleusers.FieldID, field.TypeInt32))
	_spec.From = sruq.sql
	if unique := sruq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sruq.path != nil {
		_spec.Unique = true
	}
	if fields := sruq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysroleusers.FieldID)
		for i := range fields {
			if fields[i] != sysroleusers.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sruq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sruq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sruq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sruq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sruq *SysRoleUsersQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sruq.driver.Dialect())
	t1 := builder.Table(sysroleusers.Table)
	columns := sruq.ctx.Fields
	if len(columns) == 0 {
		columns = sysroleusers.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sruq.sql != nil {
		selector = sruq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sruq.ctx.Unique != nil && *sruq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sruq.predicates {
		p(selector)
	}
	for _, p := range sruq.order {
		p(selector)
	}
	if offset := sruq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sruq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SysRoleUsersGroupBy is the group-by builder for SysRoleUsers entities.
type SysRoleUsersGroupBy struct {
	selector
	build *SysRoleUsersQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (srugb *SysRoleUsersGroupBy) Aggregate(fns ...AggregateFunc) *SysRoleUsersGroupBy {
	srugb.fns = append(srugb.fns, fns...)
	return srugb
}

// Scan applies the selector query and scans the result into the given value.
func (srugb *SysRoleUsersGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, srugb.build.ctx, "GroupBy")
	if err := srugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SysRoleUsersQuery, *SysRoleUsersGroupBy](ctx, srugb.build, srugb, srugb.build.inters, v)
}

func (srugb *SysRoleUsersGroupBy) sqlScan(ctx context.Context, root *SysRoleUsersQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(srugb.fns))
	for _, fn := range srugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*srugb.flds)+len(srugb.fns))
		for _, f := range *srugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*srugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := srugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SysRoleUsersSelect is the builder for selecting fields of SysRoleUsers entities.
type SysRoleUsersSelect struct {
	*SysRoleUsersQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (srus *SysRoleUsersSelect) Aggregate(fns ...AggregateFunc) *SysRoleUsersSelect {
	srus.fns = append(srus.fns, fns...)
	return srus
}

// Scan applies the selector query and scans the result into the given value.
func (srus *SysRoleUsersSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, srus.ctx, "Select")
	if err := srus.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SysRoleUsersQuery, *SysRoleUsersSelect](ctx, srus.SysRoleUsersQuery, srus, srus.inters, v)
}

func (srus *SysRoleUsersSelect) sqlScan(ctx context.Context, root *SysRoleUsersQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(srus.fns))
	for _, fn := range srus.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*srus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := srus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
