// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back-end/merchant/internal/data/ent/predicate"
	"back-end/merchant/internal/data/ent/sysrolepermissions"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysRolePermissionsQuery is the builder for querying SysRolePermissions entities.
type SysRolePermissionsQuery struct {
	config
	ctx        *QueryContext
	order      []sysrolepermissions.OrderOption
	inters     []Interceptor
	predicates []predicate.SysRolePermissions
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SysRolePermissionsQuery builder.
func (srpq *SysRolePermissionsQuery) Where(ps ...predicate.SysRolePermissions) *SysRolePermissionsQuery {
	srpq.predicates = append(srpq.predicates, ps...)
	return srpq
}

// Limit the number of records to be returned by this query.
func (srpq *SysRolePermissionsQuery) Limit(limit int) *SysRolePermissionsQuery {
	srpq.ctx.Limit = &limit
	return srpq
}

// Offset to start from.
func (srpq *SysRolePermissionsQuery) Offset(offset int) *SysRolePermissionsQuery {
	srpq.ctx.Offset = &offset
	return srpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (srpq *SysRolePermissionsQuery) Unique(unique bool) *SysRolePermissionsQuery {
	srpq.ctx.Unique = &unique
	return srpq
}

// Order specifies how the records should be ordered.
func (srpq *SysRolePermissionsQuery) Order(o ...sysrolepermissions.OrderOption) *SysRolePermissionsQuery {
	srpq.order = append(srpq.order, o...)
	return srpq
}

// First returns the first SysRolePermissions entity from the query.
// Returns a *NotFoundError when no SysRolePermissions was found.
func (srpq *SysRolePermissionsQuery) First(ctx context.Context) (*SysRolePermissions, error) {
	nodes, err := srpq.Limit(1).All(setContextOp(ctx, srpq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sysrolepermissions.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (srpq *SysRolePermissionsQuery) FirstX(ctx context.Context) *SysRolePermissions {
	node, err := srpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SysRolePermissions ID from the query.
// Returns a *NotFoundError when no SysRolePermissions ID was found.
func (srpq *SysRolePermissionsQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = srpq.Limit(1).IDs(setContextOp(ctx, srpq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sysrolepermissions.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (srpq *SysRolePermissionsQuery) FirstIDX(ctx context.Context) int64 {
	id, err := srpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SysRolePermissions entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SysRolePermissions entity is found.
// Returns a *NotFoundError when no SysRolePermissions entities are found.
func (srpq *SysRolePermissionsQuery) Only(ctx context.Context) (*SysRolePermissions, error) {
	nodes, err := srpq.Limit(2).All(setContextOp(ctx, srpq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sysrolepermissions.Label}
	default:
		return nil, &NotSingularError{sysrolepermissions.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (srpq *SysRolePermissionsQuery) OnlyX(ctx context.Context) *SysRolePermissions {
	node, err := srpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SysRolePermissions ID in the query.
// Returns a *NotSingularError when more than one SysRolePermissions ID is found.
// Returns a *NotFoundError when no entities are found.
func (srpq *SysRolePermissionsQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = srpq.Limit(2).IDs(setContextOp(ctx, srpq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sysrolepermissions.Label}
	default:
		err = &NotSingularError{sysrolepermissions.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (srpq *SysRolePermissionsQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := srpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SysRolePermissionsSlice.
func (srpq *SysRolePermissionsQuery) All(ctx context.Context) ([]*SysRolePermissions, error) {
	ctx = setContextOp(ctx, srpq.ctx, "All")
	if err := srpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SysRolePermissions, *SysRolePermissionsQuery]()
	return withInterceptors[[]*SysRolePermissions](ctx, srpq, qr, srpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (srpq *SysRolePermissionsQuery) AllX(ctx context.Context) []*SysRolePermissions {
	nodes, err := srpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SysRolePermissions IDs.
func (srpq *SysRolePermissionsQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if srpq.ctx.Unique == nil && srpq.path != nil {
		srpq.Unique(true)
	}
	ctx = setContextOp(ctx, srpq.ctx, "IDs")
	if err = srpq.Select(sysrolepermissions.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (srpq *SysRolePermissionsQuery) IDsX(ctx context.Context) []int64 {
	ids, err := srpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (srpq *SysRolePermissionsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, srpq.ctx, "Count")
	if err := srpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, srpq, querierCount[*SysRolePermissionsQuery](), srpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (srpq *SysRolePermissionsQuery) CountX(ctx context.Context) int {
	count, err := srpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (srpq *SysRolePermissionsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, srpq.ctx, "Exist")
	switch _, err := srpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (srpq *SysRolePermissionsQuery) ExistX(ctx context.Context) bool {
	exist, err := srpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SysRolePermissionsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (srpq *SysRolePermissionsQuery) Clone() *SysRolePermissionsQuery {
	if srpq == nil {
		return nil
	}
	return &SysRolePermissionsQuery{
		config:     srpq.config,
		ctx:        srpq.ctx.Clone(),
		order:      append([]sysrolepermissions.OrderOption{}, srpq.order...),
		inters:     append([]Interceptor{}, srpq.inters...),
		predicates: append([]predicate.SysRolePermissions{}, srpq.predicates...),
		// clone intermediate query.
		sql:  srpq.sql.Clone(),
		path: srpq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RoleID int64 `json:"role_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SysRolePermissions.Query().
//		GroupBy(sysrolepermissions.FieldRoleID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (srpq *SysRolePermissionsQuery) GroupBy(field string, fields ...string) *SysRolePermissionsGroupBy {
	srpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SysRolePermissionsGroupBy{build: srpq}
	grbuild.flds = &srpq.ctx.Fields
	grbuild.label = sysrolepermissions.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RoleID int64 `json:"role_id,omitempty"`
//	}
//
//	client.SysRolePermissions.Query().
//		Select(sysrolepermissions.FieldRoleID).
//		Scan(ctx, &v)
func (srpq *SysRolePermissionsQuery) Select(fields ...string) *SysRolePermissionsSelect {
	srpq.ctx.Fields = append(srpq.ctx.Fields, fields...)
	sbuild := &SysRolePermissionsSelect{SysRolePermissionsQuery: srpq}
	sbuild.label = sysrolepermissions.Label
	sbuild.flds, sbuild.scan = &srpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SysRolePermissionsSelect configured with the given aggregations.
func (srpq *SysRolePermissionsQuery) Aggregate(fns ...AggregateFunc) *SysRolePermissionsSelect {
	return srpq.Select().Aggregate(fns...)
}

func (srpq *SysRolePermissionsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range srpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, srpq); err != nil {
				return err
			}
		}
	}
	for _, f := range srpq.ctx.Fields {
		if !sysrolepermissions.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if srpq.path != nil {
		prev, err := srpq.path(ctx)
		if err != nil {
			return err
		}
		srpq.sql = prev
	}
	return nil
}

func (srpq *SysRolePermissionsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SysRolePermissions, error) {
	var (
		nodes = []*SysRolePermissions{}
		_spec = srpq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SysRolePermissions).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SysRolePermissions{config: srpq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, srpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (srpq *SysRolePermissionsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := srpq.querySpec()
	_spec.Node.Columns = srpq.ctx.Fields
	if len(srpq.ctx.Fields) > 0 {
		_spec.Unique = srpq.ctx.Unique != nil && *srpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, srpq.driver, _spec)
}

func (srpq *SysRolePermissionsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sysrolepermissions.Table, sysrolepermissions.Columns, sqlgraph.NewFieldSpec(sysrolepermissions.FieldID, field.TypeInt64))
	_spec.From = srpq.sql
	if unique := srpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if srpq.path != nil {
		_spec.Unique = true
	}
	if fields := srpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysrolepermissions.FieldID)
		for i := range fields {
			if fields[i] != sysrolepermissions.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := srpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := srpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := srpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := srpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (srpq *SysRolePermissionsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(srpq.driver.Dialect())
	t1 := builder.Table(sysrolepermissions.Table)
	columns := srpq.ctx.Fields
	if len(columns) == 0 {
		columns = sysrolepermissions.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if srpq.sql != nil {
		selector = srpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if srpq.ctx.Unique != nil && *srpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range srpq.predicates {
		p(selector)
	}
	for _, p := range srpq.order {
		p(selector)
	}
	if offset := srpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := srpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SysRolePermissionsGroupBy is the group-by builder for SysRolePermissions entities.
type SysRolePermissionsGroupBy struct {
	selector
	build *SysRolePermissionsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (srpgb *SysRolePermissionsGroupBy) Aggregate(fns ...AggregateFunc) *SysRolePermissionsGroupBy {
	srpgb.fns = append(srpgb.fns, fns...)
	return srpgb
}

// Scan applies the selector query and scans the result into the given value.
func (srpgb *SysRolePermissionsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, srpgb.build.ctx, "GroupBy")
	if err := srpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SysRolePermissionsQuery, *SysRolePermissionsGroupBy](ctx, srpgb.build, srpgb, srpgb.build.inters, v)
}

func (srpgb *SysRolePermissionsGroupBy) sqlScan(ctx context.Context, root *SysRolePermissionsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(srpgb.fns))
	for _, fn := range srpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*srpgb.flds)+len(srpgb.fns))
		for _, f := range *srpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*srpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := srpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SysRolePermissionsSelect is the builder for selecting fields of SysRolePermissions entities.
type SysRolePermissionsSelect struct {
	*SysRolePermissionsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (srps *SysRolePermissionsSelect) Aggregate(fns ...AggregateFunc) *SysRolePermissionsSelect {
	srps.fns = append(srps.fns, fns...)
	return srps
}

// Scan applies the selector query and scans the result into the given value.
func (srps *SysRolePermissionsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, srps.ctx, "Select")
	if err := srps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SysRolePermissionsQuery, *SysRolePermissionsSelect](ctx, srps.SysRolePermissionsQuery, srps, srps.inters, v)
}

func (srps *SysRolePermissionsSelect) sqlScan(ctx context.Context, root *SysRolePermissionsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(srps.fns))
	for _, fn := range srps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*srps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := srps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
