// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back-end/merchant/internal/data/ent/sysroleusers"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SysRoleUsers is the model entity for the SysRoleUsers schema.
type SysRoleUsers struct {
	config `json:"-"`
	// ID of the ent.
	ID int32 `json:"id,omitempty"`
	// RoleID holds the value of the "role_id" field.
	RoleID int64 `json:"role_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime int32 `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime   int32 `json:"update_time,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysRoleUsers) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysroleusers.FieldID, sysroleusers.FieldRoleID, sysroleusers.FieldUserID, sysroleusers.FieldCreateTime, sysroleusers.FieldUpdateTime:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysRoleUsers fields.
func (sru *SysRoleUsers) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysroleusers.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sru.ID = int32(value.Int64)
		case sysroleusers.FieldRoleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				sru.RoleID = value.Int64
			}
		case sysroleusers.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				sru.UserID = value.Int64
			}
		case sysroleusers.FieldCreateTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				sru.CreateTime = int32(value.Int64)
			}
		case sysroleusers.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				sru.UpdateTime = int32(value.Int64)
			}
		default:
			sru.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysRoleUsers.
// This includes values selected through modifiers, order, etc.
func (sru *SysRoleUsers) Value(name string) (ent.Value, error) {
	return sru.selectValues.Get(name)
}

// Update returns a builder for updating this SysRoleUsers.
// Note that you need to call SysRoleUsers.Unwrap() before calling this method if this SysRoleUsers
// was returned from a transaction, and the transaction was committed or rolled back.
func (sru *SysRoleUsers) Update() *SysRoleUsersUpdateOne {
	return NewSysRoleUsersClient(sru.config).UpdateOne(sru)
}

// Unwrap unwraps the SysRoleUsers entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sru *SysRoleUsers) Unwrap() *SysRoleUsers {
	_tx, ok := sru.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysRoleUsers is not a transactional entity")
	}
	sru.config.driver = _tx.drv
	return sru
}

// String implements the fmt.Stringer.
func (sru *SysRoleUsers) String() string {
	var builder strings.Builder
	builder.WriteString("SysRoleUsers(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sru.ID))
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", sru.RoleID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", sru.UserID))
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(fmt.Sprintf("%v", sru.CreateTime))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(fmt.Sprintf("%v", sru.UpdateTime))
	builder.WriteByte(')')
	return builder.String()
}

// SysRoleUsersSlice is a parsable slice of SysRoleUsers.
type SysRoleUsersSlice []*SysRoleUsers
