// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back-end/merchant/internal/data/ent/predicate"
	"back-end/merchant/internal/data/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetGUID sets the "guid" field.
func (uu *UserUpdate) SetGUID(s string) *UserUpdate {
	uu.mutation.SetGUID(s)
	return uu
}

// SetNillableGUID sets the "guid" field if the given value is not nil.
func (uu *UserUpdate) SetNillableGUID(s *string) *UserUpdate {
	if s != nil {
		uu.SetGUID(*s)
	}
	return uu
}

// SetUsername sets the "username" field.
func (uu *UserUpdate) SetUsername(s string) *UserUpdate {
	uu.mutation.SetUsername(s)
	return uu
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (uu *UserUpdate) SetNillableUsername(s *string) *UserUpdate {
	if s != nil {
		uu.SetUsername(*s)
	}
	return uu
}

// SetPassword sets the "password" field.
func (uu *UserUpdate) SetPassword(s string) *UserUpdate {
	uu.mutation.SetPassword(s)
	return uu
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (uu *UserUpdate) SetNillablePassword(s *string) *UserUpdate {
	if s != nil {
		uu.SetPassword(*s)
	}
	return uu
}

// SetNickName sets the "nick_name" field.
func (uu *UserUpdate) SetNickName(s string) *UserUpdate {
	uu.mutation.SetNickName(s)
	return uu
}

// SetNillableNickName sets the "nick_name" field if the given value is not nil.
func (uu *UserUpdate) SetNillableNickName(s *string) *UserUpdate {
	if s != nil {
		uu.SetNickName(*s)
	}
	return uu
}

// SetMerchantID sets the "merchant_id" field.
func (uu *UserUpdate) SetMerchantID(i int64) *UserUpdate {
	uu.mutation.ResetMerchantID()
	uu.mutation.SetMerchantID(i)
	return uu
}

// SetNillableMerchantID sets the "merchant_id" field if the given value is not nil.
func (uu *UserUpdate) SetNillableMerchantID(i *int64) *UserUpdate {
	if i != nil {
		uu.SetMerchantID(*i)
	}
	return uu
}

// AddMerchantID adds i to the "merchant_id" field.
func (uu *UserUpdate) AddMerchantID(i int64) *UserUpdate {
	uu.mutation.AddMerchantID(i)
	return uu
}

// SetRole sets the "role" field.
func (uu *UserUpdate) SetRole(s string) *UserUpdate {
	uu.mutation.SetRole(s)
	return uu
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (uu *UserUpdate) SetNillableRole(s *string) *UserUpdate {
	if s != nil {
		uu.SetRole(*s)
	}
	return uu
}

// SetAvatar sets the "avatar" field.
func (uu *UserUpdate) SetAvatar(s string) *UserUpdate {
	uu.mutation.SetAvatar(s)
	return uu
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (uu *UserUpdate) SetNillableAvatar(s *string) *UserUpdate {
	if s != nil {
		uu.SetAvatar(*s)
	}
	return uu
}

// ClearAvatar clears the value of the "avatar" field.
func (uu *UserUpdate) ClearAvatar() *UserUpdate {
	uu.mutation.ClearAvatar()
	return uu
}

// SetEmail sets the "email" field.
func (uu *UserUpdate) SetEmail(s string) *UserUpdate {
	uu.mutation.SetEmail(s)
	return uu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (uu *UserUpdate) SetNillableEmail(s *string) *UserUpdate {
	if s != nil {
		uu.SetEmail(*s)
	}
	return uu
}

// SetPhone sets the "phone" field.
func (uu *UserUpdate) SetPhone(s string) *UserUpdate {
	uu.mutation.SetPhone(s)
	return uu
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (uu *UserUpdate) SetNillablePhone(s *string) *UserUpdate {
	if s != nil {
		uu.SetPhone(*s)
	}
	return uu
}

// SetIsMaster sets the "is_master" field.
func (uu *UserUpdate) SetIsMaster(i int16) *UserUpdate {
	uu.mutation.ResetIsMaster()
	uu.mutation.SetIsMaster(i)
	return uu
}

// SetNillableIsMaster sets the "is_master" field if the given value is not nil.
func (uu *UserUpdate) SetNillableIsMaster(i *int16) *UserUpdate {
	if i != nil {
		uu.SetIsMaster(*i)
	}
	return uu
}

// AddIsMaster adds i to the "is_master" field.
func (uu *UserUpdate) AddIsMaster(i int16) *UserUpdate {
	uu.mutation.AddIsMaster(i)
	return uu
}

// SetCreateTime sets the "create_time" field.
func (uu *UserUpdate) SetCreateTime(i int32) *UserUpdate {
	uu.mutation.ResetCreateTime()
	uu.mutation.SetCreateTime(i)
	return uu
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (uu *UserUpdate) SetNillableCreateTime(i *int32) *UserUpdate {
	if i != nil {
		uu.SetCreateTime(*i)
	}
	return uu
}

// AddCreateTime adds i to the "create_time" field.
func (uu *UserUpdate) AddCreateTime(i int32) *UserUpdate {
	uu.mutation.AddCreateTime(i)
	return uu
}

// SetUpdateTime sets the "update_time" field.
func (uu *UserUpdate) SetUpdateTime(i int32) *UserUpdate {
	uu.mutation.ResetUpdateTime()
	uu.mutation.SetUpdateTime(i)
	return uu
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (uu *UserUpdate) SetNillableUpdateTime(i *int32) *UserUpdate {
	if i != nil {
		uu.SetUpdateTime(*i)
	}
	return uu
}

// AddUpdateTime adds i to the "update_time" field.
func (uu *UserUpdate) AddUpdateTime(i int32) *UserUpdate {
	uu.mutation.AddUpdateTime(i)
	return uu
}

// SetLastLoginTime sets the "last_login_time" field.
func (uu *UserUpdate) SetLastLoginTime(i int32) *UserUpdate {
	uu.mutation.ResetLastLoginTime()
	uu.mutation.SetLastLoginTime(i)
	return uu
}

// SetNillableLastLoginTime sets the "last_login_time" field if the given value is not nil.
func (uu *UserUpdate) SetNillableLastLoginTime(i *int32) *UserUpdate {
	if i != nil {
		uu.SetLastLoginTime(*i)
	}
	return uu
}

// AddLastLoginTime adds i to the "last_login_time" field.
func (uu *UserUpdate) AddLastLoginTime(i int32) *UserUpdate {
	uu.mutation.AddLastLoginTime(i)
	return uu
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.GUID(); ok {
		_spec.SetField(user.FieldGUID, field.TypeString, value)
	}
	if value, ok := uu.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := uu.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := uu.mutation.NickName(); ok {
		_spec.SetField(user.FieldNickName, field.TypeString, value)
	}
	if value, ok := uu.mutation.MerchantID(); ok {
		_spec.SetField(user.FieldMerchantID, field.TypeInt64, value)
	}
	if value, ok := uu.mutation.AddedMerchantID(); ok {
		_spec.AddField(user.FieldMerchantID, field.TypeInt64, value)
	}
	if value, ok := uu.mutation.Role(); ok {
		_spec.SetField(user.FieldRole, field.TypeString, value)
	}
	if value, ok := uu.mutation.Avatar(); ok {
		_spec.SetField(user.FieldAvatar, field.TypeString, value)
	}
	if uu.mutation.AvatarCleared() {
		_spec.ClearField(user.FieldAvatar, field.TypeString)
	}
	if value, ok := uu.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := uu.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
	}
	if value, ok := uu.mutation.IsMaster(); ok {
		_spec.SetField(user.FieldIsMaster, field.TypeInt16, value)
	}
	if value, ok := uu.mutation.AddedIsMaster(); ok {
		_spec.AddField(user.FieldIsMaster, field.TypeInt16, value)
	}
	if value, ok := uu.mutation.CreateTime(); ok {
		_spec.SetField(user.FieldCreateTime, field.TypeInt32, value)
	}
	if value, ok := uu.mutation.AddedCreateTime(); ok {
		_spec.AddField(user.FieldCreateTime, field.TypeInt32, value)
	}
	if value, ok := uu.mutation.UpdateTime(); ok {
		_spec.SetField(user.FieldUpdateTime, field.TypeInt32, value)
	}
	if value, ok := uu.mutation.AddedUpdateTime(); ok {
		_spec.AddField(user.FieldUpdateTime, field.TypeInt32, value)
	}
	if value, ok := uu.mutation.LastLoginTime(); ok {
		_spec.SetField(user.FieldLastLoginTime, field.TypeInt32, value)
	}
	if value, ok := uu.mutation.AddedLastLoginTime(); ok {
		_spec.AddField(user.FieldLastLoginTime, field.TypeInt32, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetGUID sets the "guid" field.
func (uuo *UserUpdateOne) SetGUID(s string) *UserUpdateOne {
	uuo.mutation.SetGUID(s)
	return uuo
}

// SetNillableGUID sets the "guid" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableGUID(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetGUID(*s)
	}
	return uuo
}

// SetUsername sets the "username" field.
func (uuo *UserUpdateOne) SetUsername(s string) *UserUpdateOne {
	uuo.mutation.SetUsername(s)
	return uuo
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableUsername(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetUsername(*s)
	}
	return uuo
}

// SetPassword sets the "password" field.
func (uuo *UserUpdateOne) SetPassword(s string) *UserUpdateOne {
	uuo.mutation.SetPassword(s)
	return uuo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillablePassword(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetPassword(*s)
	}
	return uuo
}

// SetNickName sets the "nick_name" field.
func (uuo *UserUpdateOne) SetNickName(s string) *UserUpdateOne {
	uuo.mutation.SetNickName(s)
	return uuo
}

// SetNillableNickName sets the "nick_name" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableNickName(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetNickName(*s)
	}
	return uuo
}

// SetMerchantID sets the "merchant_id" field.
func (uuo *UserUpdateOne) SetMerchantID(i int64) *UserUpdateOne {
	uuo.mutation.ResetMerchantID()
	uuo.mutation.SetMerchantID(i)
	return uuo
}

// SetNillableMerchantID sets the "merchant_id" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableMerchantID(i *int64) *UserUpdateOne {
	if i != nil {
		uuo.SetMerchantID(*i)
	}
	return uuo
}

// AddMerchantID adds i to the "merchant_id" field.
func (uuo *UserUpdateOne) AddMerchantID(i int64) *UserUpdateOne {
	uuo.mutation.AddMerchantID(i)
	return uuo
}

// SetRole sets the "role" field.
func (uuo *UserUpdateOne) SetRole(s string) *UserUpdateOne {
	uuo.mutation.SetRole(s)
	return uuo
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableRole(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetRole(*s)
	}
	return uuo
}

// SetAvatar sets the "avatar" field.
func (uuo *UserUpdateOne) SetAvatar(s string) *UserUpdateOne {
	uuo.mutation.SetAvatar(s)
	return uuo
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableAvatar(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetAvatar(*s)
	}
	return uuo
}

// ClearAvatar clears the value of the "avatar" field.
func (uuo *UserUpdateOne) ClearAvatar() *UserUpdateOne {
	uuo.mutation.ClearAvatar()
	return uuo
}

// SetEmail sets the "email" field.
func (uuo *UserUpdateOne) SetEmail(s string) *UserUpdateOne {
	uuo.mutation.SetEmail(s)
	return uuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableEmail(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetEmail(*s)
	}
	return uuo
}

// SetPhone sets the "phone" field.
func (uuo *UserUpdateOne) SetPhone(s string) *UserUpdateOne {
	uuo.mutation.SetPhone(s)
	return uuo
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillablePhone(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetPhone(*s)
	}
	return uuo
}

// SetIsMaster sets the "is_master" field.
func (uuo *UserUpdateOne) SetIsMaster(i int16) *UserUpdateOne {
	uuo.mutation.ResetIsMaster()
	uuo.mutation.SetIsMaster(i)
	return uuo
}

// SetNillableIsMaster sets the "is_master" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableIsMaster(i *int16) *UserUpdateOne {
	if i != nil {
		uuo.SetIsMaster(*i)
	}
	return uuo
}

// AddIsMaster adds i to the "is_master" field.
func (uuo *UserUpdateOne) AddIsMaster(i int16) *UserUpdateOne {
	uuo.mutation.AddIsMaster(i)
	return uuo
}

// SetCreateTime sets the "create_time" field.
func (uuo *UserUpdateOne) SetCreateTime(i int32) *UserUpdateOne {
	uuo.mutation.ResetCreateTime()
	uuo.mutation.SetCreateTime(i)
	return uuo
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableCreateTime(i *int32) *UserUpdateOne {
	if i != nil {
		uuo.SetCreateTime(*i)
	}
	return uuo
}

// AddCreateTime adds i to the "create_time" field.
func (uuo *UserUpdateOne) AddCreateTime(i int32) *UserUpdateOne {
	uuo.mutation.AddCreateTime(i)
	return uuo
}

// SetUpdateTime sets the "update_time" field.
func (uuo *UserUpdateOne) SetUpdateTime(i int32) *UserUpdateOne {
	uuo.mutation.ResetUpdateTime()
	uuo.mutation.SetUpdateTime(i)
	return uuo
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableUpdateTime(i *int32) *UserUpdateOne {
	if i != nil {
		uuo.SetUpdateTime(*i)
	}
	return uuo
}

// AddUpdateTime adds i to the "update_time" field.
func (uuo *UserUpdateOne) AddUpdateTime(i int32) *UserUpdateOne {
	uuo.mutation.AddUpdateTime(i)
	return uuo
}

// SetLastLoginTime sets the "last_login_time" field.
func (uuo *UserUpdateOne) SetLastLoginTime(i int32) *UserUpdateOne {
	uuo.mutation.ResetLastLoginTime()
	uuo.mutation.SetLastLoginTime(i)
	return uuo
}

// SetNillableLastLoginTime sets the "last_login_time" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableLastLoginTime(i *int32) *UserUpdateOne {
	if i != nil {
		uuo.SetLastLoginTime(*i)
	}
	return uuo
}

// AddLastLoginTime adds i to the "last_login_time" field.
func (uuo *UserUpdateOne) AddLastLoginTime(i int32) *UserUpdateOne {
	uuo.mutation.AddLastLoginTime(i)
	return uuo
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uuo *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.GUID(); ok {
		_spec.SetField(user.FieldGUID, field.TypeString, value)
	}
	if value, ok := uuo.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := uuo.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := uuo.mutation.NickName(); ok {
		_spec.SetField(user.FieldNickName, field.TypeString, value)
	}
	if value, ok := uuo.mutation.MerchantID(); ok {
		_spec.SetField(user.FieldMerchantID, field.TypeInt64, value)
	}
	if value, ok := uuo.mutation.AddedMerchantID(); ok {
		_spec.AddField(user.FieldMerchantID, field.TypeInt64, value)
	}
	if value, ok := uuo.mutation.Role(); ok {
		_spec.SetField(user.FieldRole, field.TypeString, value)
	}
	if value, ok := uuo.mutation.Avatar(); ok {
		_spec.SetField(user.FieldAvatar, field.TypeString, value)
	}
	if uuo.mutation.AvatarCleared() {
		_spec.ClearField(user.FieldAvatar, field.TypeString)
	}
	if value, ok := uuo.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := uuo.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
	}
	if value, ok := uuo.mutation.IsMaster(); ok {
		_spec.SetField(user.FieldIsMaster, field.TypeInt16, value)
	}
	if value, ok := uuo.mutation.AddedIsMaster(); ok {
		_spec.AddField(user.FieldIsMaster, field.TypeInt16, value)
	}
	if value, ok := uuo.mutation.CreateTime(); ok {
		_spec.SetField(user.FieldCreateTime, field.TypeInt32, value)
	}
	if value, ok := uuo.mutation.AddedCreateTime(); ok {
		_spec.AddField(user.FieldCreateTime, field.TypeInt32, value)
	}
	if value, ok := uuo.mutation.UpdateTime(); ok {
		_spec.SetField(user.FieldUpdateTime, field.TypeInt32, value)
	}
	if value, ok := uuo.mutation.AddedUpdateTime(); ok {
		_spec.AddField(user.FieldUpdateTime, field.TypeInt32, value)
	}
	if value, ok := uuo.mutation.LastLoginTime(); ok {
		_spec.SetField(user.FieldLastLoginTime, field.TypeInt32, value)
	}
	if value, ok := uuo.mutation.AddedLastLoginTime(); ok {
		_spec.AddField(user.FieldLastLoginTime, field.TypeInt32, value)
	}
	_node = &User{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
