// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// MerchantChannelBind is the predicate function for merchantchannelbind builders.
type MerchantChannelBind func(*sql.Selector)

// MerchantList is the predicate function for merchantlist builders.
type MerchantList func(*sql.Selector)

// SysMenu is the predicate function for sysmenu builders.
type SysMenu func(*sql.Selector)

// SysPermissions is the predicate function for syspermissions builders.
type SysPermissions func(*sql.Selector)

// SysRoleMenu is the predicate function for sysrolemenu builders.
type SysRoleMenu func(*sql.Selector)

// SysRolePermissions is the predicate function for sysrolepermissions builders.
type SysRolePermissions func(*sql.Selector)

// SysRoleUsers is the predicate function for sysroleusers builders.
type SysRoleUsers func(*sql.Selector)

// SysRoles is the predicate function for sysroles builders.
type SysRoles func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
