// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MerchantChannelBindColumns holds the columns for the "merchant_channel_bind" table.
	MerchantChannelBindColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt32, Increment: true, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "merchant_id", Type: field.TypeInt32, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "channel_id", Type: field.TypeInt32, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "status", Type: field.TypeInt16, SchemaType: map[string]string{"mysql": "smallint"}},
		{Name: "create_time", Type: field.TypeInt32, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "update_time", Type: field.TypeInt32, SchemaType: map[string]string{"mysql": "int"}},
	}
	// MerchantChannelBindTable holds the schema information for the "merchant_channel_bind" table.
	MerchantChannelBindTable = &schema.Table{
		Name:       "merchant_channel_bind",
		Columns:    MerchantChannelBindColumns,
		PrimaryKey: []*schema.Column{MerchantChannelBindColumns[0]},
	}
	// MerchantListColumns holds the columns for the "merchant_list" table.
	MerchantListColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt32, Increment: true, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "guid", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(100)"}},
		{Name: "name", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(200)"}},
		{Name: "host", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(200)"}},
		{Name: "manage_host", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(100)"}},
		{Name: "status", Type: field.TypeInt16, SchemaType: map[string]string{"mysql": "smallint"}},
		{Name: "create_time", Type: field.TypeInt32, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "update_time", Type: field.TypeInt32, SchemaType: map[string]string{"mysql": "int"}},
	}
	// MerchantListTable holds the schema information for the "merchant_list" table.
	MerchantListTable = &schema.Table{
		Name:       "merchant_list",
		Columns:    MerchantListColumns,
		PrimaryKey: []*schema.Column{MerchantListColumns[0]},
	}
	// SysMenuColumns holds the columns for the "sys_menu" table.
	SysMenuColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "parent_id", Type: field.TypeInt64, Default: 0, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "title", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(50)"}},
		{Name: "icon", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "varchar(50)"}},
		{Name: "uri", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "varchar(50)"}},
		{Name: "show", Type: field.TypeInt8, Default: 1, SchemaType: map[string]string{"mysql": "tinyint"}},
		{Name: "sort", Type: field.TypeInt32, Default: 0, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "create_time", Type: field.TypeInt32, Default: 0, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "update_time", Type: field.TypeInt32, Default: 0, SchemaType: map[string]string{"mysql": "int"}},
	}
	// SysMenuTable holds the schema information for the "sys_menu" table.
	SysMenuTable = &schema.Table{
		Name:       "sys_menu",
		Columns:    SysMenuColumns,
		PrimaryKey: []*schema.Column{SysMenuColumns[0]},
	}
	// SysPermissionsColumns holds the columns for the "sys_permissions" table.
	SysPermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "menu_id", Type: field.TypeInt64, Default: 0, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "name", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(50)"}},
		{Name: "code", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(50)"}},
		{Name: "path", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(100)"}},
		{Name: "command", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(100)"}},
		{Name: "create_time", Type: field.TypeInt32, Default: 0, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "update_time", Type: field.TypeInt32, Default: 0, SchemaType: map[string]string{"mysql": "int"}},
	}
	// SysPermissionsTable holds the schema information for the "sys_permissions" table.
	SysPermissionsTable = &schema.Table{
		Name:       "sys_permissions",
		Columns:    SysPermissionsColumns,
		PrimaryKey: []*schema.Column{SysPermissionsColumns[0]},
	}
	// SysRoleMenuColumns holds the columns for the "sys_role_menu" table.
	SysRoleMenuColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "role_id", Type: field.TypeInt64, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "menu_id", Type: field.TypeInt64, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "create_time", Type: field.TypeInt32, Default: 0, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "update_time", Type: field.TypeInt32, Default: 0, SchemaType: map[string]string{"mysql": "int"}},
	}
	// SysRoleMenuTable holds the schema information for the "sys_role_menu" table.
	SysRoleMenuTable = &schema.Table{
		Name:       "sys_role_menu",
		Columns:    SysRoleMenuColumns,
		PrimaryKey: []*schema.Column{SysRoleMenuColumns[0]},
	}
	// SysRolePermissionsColumns holds the columns for the "sys_role_permissions" table.
	SysRolePermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "role_id", Type: field.TypeInt64, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "permission_id", Type: field.TypeInt64, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "create_time", Type: field.TypeInt32, Default: 0, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "update_time", Type: field.TypeInt32, Default: 0, SchemaType: map[string]string{"mysql": "int"}},
	}
	// SysRolePermissionsTable holds the schema information for the "sys_role_permissions" table.
	SysRolePermissionsTable = &schema.Table{
		Name:       "sys_role_permissions",
		Columns:    SysRolePermissionsColumns,
		PrimaryKey: []*schema.Column{SysRolePermissionsColumns[0]},
	}
	// SysRoleUsersColumns holds the columns for the "sys_role_users" table.
	SysRoleUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt32, Increment: true, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "role_id", Type: field.TypeInt64, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "user_id", Type: field.TypeInt64, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "create_time", Type: field.TypeInt32, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "update_time", Type: field.TypeInt32, Default: 0, SchemaType: map[string]string{"mysql": "int"}},
	}
	// SysRoleUsersTable holds the schema information for the "sys_role_users" table.
	SysRoleUsersTable = &schema.Table{
		Name:       "sys_role_users",
		Columns:    SysRoleUsersColumns,
		PrimaryKey: []*schema.Column{SysRoleUsersColumns[0]},
	}
	// SysRolesColumns holds the columns for the "sys_roles" table.
	SysRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "guid", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(100)"}},
		{Name: "merchant_id", Type: field.TypeInt64, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "name", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(50)"}},
		{Name: "code", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(50)"}},
		{Name: "create_time", Type: field.TypeInt32, Default: 0, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "update_time", Type: field.TypeInt32, Default: 0, SchemaType: map[string]string{"mysql": "int"}},
	}
	// SysRolesTable holds the schema information for the "sys_roles" table.
	SysRolesTable = &schema.Table{
		Name:       "sys_roles",
		Columns:    SysRolesColumns,
		PrimaryKey: []*schema.Column{SysRolesColumns[0]},
	}
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "guid", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(100)"}},
		{Name: "username", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(100)"}},
		{Name: "password", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(100)"}},
		{Name: "nick_name", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(100)"}},
		{Name: "merchant_id", Type: field.TypeInt64, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "role", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(200)"}},
		{Name: "avatar", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "varchar(500)"}},
		{Name: "email", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(100)"}},
		{Name: "phone", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(100)"}},
		{Name: "is_master", Type: field.TypeInt16, SchemaType: map[string]string{"mysql": "smallint"}},
		{Name: "create_time", Type: field.TypeInt32, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "update_time", Type: field.TypeInt32, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "last_login_time", Type: field.TypeInt32, SchemaType: map[string]string{"mysql": "int"}},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MerchantChannelBindTable,
		MerchantListTable,
		SysMenuTable,
		SysPermissionsTable,
		SysRoleMenuTable,
		SysRolePermissionsTable,
		SysRoleUsersTable,
		SysRolesTable,
		UserTable,
	}
)

func init() {
	MerchantChannelBindTable.Annotation = &entsql.Annotation{
		Table: "merchant_channel_bind",
	}
	MerchantListTable.Annotation = &entsql.Annotation{
		Table: "merchant_list",
	}
	SysMenuTable.Annotation = &entsql.Annotation{
		Table: "sys_menu",
	}
	SysPermissionsTable.Annotation = &entsql.Annotation{
		Table: "sys_permissions",
	}
	SysRoleMenuTable.Annotation = &entsql.Annotation{
		Table: "sys_role_menu",
	}
	SysRolePermissionsTable.Annotation = &entsql.Annotation{
		Table: "sys_role_permissions",
	}
	SysRoleUsersTable.Annotation = &entsql.Annotation{
		Table: "sys_role_users",
	}
	SysRolesTable.Annotation = &entsql.Annotation{
		Table: "sys_roles",
	}
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
}
